### ISSUE TITLE
Настроить detekt

### ISSUE THREAD

**Issue by n-shvedov27** [davay-project/davay_posmotrim_android#39]
- Добавить в проект [правила](https://pastebin.com/iND7fhpe) detekt
- Настроить их прогон в app, uikit, uikit-sample

Полезные материалы

- https://habr.com/ru/articles/442500/
- https://github.com/detekt/detekt

**Comment by dvBuslaev** [comment]
если я беру конфиг который ты мне прислал то я получаю ошибку
Run failed with 1 invalid config property.
        - Property 'formatting' is misspelled or does not exist.
        - Property 'formatting>Indentation>continuationIndentSize' is deprecated. `continuationIndentSize` is ignored by KtLint and will have no effect.

если я использую тот, который мне сгенерил detect, то он билдится с ошибкой, но если запускать с флагом --scan то он в консоле показывает где ошибки в коде


![Image](https://github.com/davay-project/davay_posmotrim_android/assets/128169060/b06df897-7f18-4041-b04d-5727ffa92f23)

так и должно быть?

**Comment by dvBuslaev** [comment]
@n-shvedov27 тегну на всякий случай)

**Comment by n-shvedov27** [comment]
Тебе нужна gradle-зависимость от detekt-formatting

**Comment by n-shvedov27** [comment]
Ошибки на скрине - это ошибки форматирования в коде
Их нужно исправить и тогда детект пройдет успешно)

**Comment by dvBuslaev** [comment]
я честно хз, я ковырял ковырял, пытался этот форматтинг засунуть, у меня не встает, не понимаю куда ему эту зависимость пихать

**Comment by n-shvedov27** [comment]
Давай я тебе скину пример с еще одного проекта. По аналогии думаю проще будет сделать


![Image](https://github.com/davay-project/davay_posmotrim_android/assets/37715977/dea4abc5-95b4-4e19-a81f-3d756a8595fd)
![Image](https://github.com/davay-project/davay_posmotrim_android/assets/37715977/72576393-ecaf-47b7-a2b0-0f021c3b15ce)
![Image](https://github.com/davay-project/davay_posmotrim_android/assets/37715977/55d9e812-accc-45f7-ad15-72a426f2d472)
![Image](https://github.com/davay-project/davay_posmotrim_android/assets/37715977/1197ab30-ceed-41d2-bc71-ea2f17320240)

**Comment by n-shvedov27** [comment]
Ну и на CI добавить run: ./gradlew detekt
