### ISSUE TITLE
Настройка проекта

### ISSUE THREAD

**Issue by n-shvedov27** [davay-project/davay_posmotrim_android#9]
### Gradle

Запушить шаблон приложения в репозиторий
- applicationId: com.davayposmotrim.android
- minSdk: 26
- targetSdk/compileSdk: 34
- build: Gradle 8.2+KTS

### GitFlow

- dev и main протектед ветки(в dev пушим только через pr)
- Добавить @n-shvedov27 кодовнером

**Comment by dvBuslaev** [comment]
Все сделано
